apiVersion: v2
name: intersect
description: Unified deployment for INTERSECT core services and test adapters
type: application
version: 0.0.2
dependencies:
  # message plane
  - alias: intersect-message-broker-1
    condition: intersect-message-broker-1.enabled
    name: rabbitmq
    version: "14.x.x" # versions >=15 use RabbitMQ v4
    repository: "oci://registry-1.docker.io/bitnamicharts"

  # data plane
  - alias: intersect-storage-1
    condition: intersect-storage-1.enabled
    name: minio
    version: "14.x.x"
    repository: "oci://registry-1.docker.io/bitnamicharts"
